### ISSUE TITLE
nextjs build+export

### ISSUE THREAD

**Issue by jaanauati** [jaanauati/react-dfp#87]
```
(node:35459) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at doloadGPTScript (/Users/jonatan/projects/react-dfp-surge/node_modules/react-dfp/lib/utils.js:9:3)
    at /Users/jonatan/projects/react-dfp-surge/node_modules/react-dfp/lib/utils.js:29:5
    at new Promise (<anonymous>)
    at Object.loadGPTScript (/Users/jonatan/projects/react-dfp-surge/node_modules/react-dfp/lib/utils.js:28:10)
    at EventEmitter.getGoogletag (/Users/jonatan/projects/react-dfp-surge/node_modules/react-dfp/lib/manager.js:132:42)
    at EventEmitter.init (/Users/jonatan/projects/react-dfp-surge/node_modules/react-dfp/lib/manager.js:92:12)
    at EventEmitter.doLoad (/Users/jonatan/projects/react-dfp-surge/node_modules/react-dfp/lib/manager.js:155:10)
    at EventEmitter.load (/Users/jonatan/projects/react-dfp-surge/node_modules/react-dfp/lib/manager.js:148:26)
    at Module.<anonymous> (/Users/jonatan/projects/react-dfp-surge/.next/server/static/i0iUOVpMWpyfeE9xt0Qwf/pages/basic.js:230:54)
    at __webpack_require__ (/Users/jonatan/projects/react-dfp-surge/.next/server/static/i0iUOVpMWpyfeE9xt0Qwf/pages/basic.js:23:31)
```

**Comment by jaanauati** [comment]
@rhaze are u still experiencing issues?, keep in mind that calls to `load()` and `refresh()` need to be made only after the component is mounted at browser side, so you typically will have to place them into `componentDidMount() { }`.

**Comment by scott-thrillist** [comment]
We're using react-dfp with Next.js v9 with no issues. For client side operations don't forget to make use of `if (process.browser) {...}`
